routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return view('home');
});

Route::get('instructions/search', 'InstructionDetailController@filter')->name('instrunctions.search');

Route::resource('instructions', 'InstructionDetailController');

Route::patch('instructions/{instruction}/delivered', 'InstructionDetailController@delivered')->name('instruction.delivered');

Route::get('members', 'BranchMembersController@index')->name('members.index');

Route::get('members/create', 'BranchMembersController@create')->name('members.create');

Route::post('members', 'BranchMembersController@store')->name('members.store');

Route::delete('members/{member}', 'BranchMembersController@destroy')->name('members.destroy');

Route::get('account_registered', 'BranchMembersController@account_registered')->name('account_registered');

Route::post('activate_account', 'BranchMembersController@activate_account')->name('activate_account');

Auth::routes();

Route::get('settings', 'SettingsController@page')->name('settings');

Route::patch('settings/change/email', 'SettingsController@change_email')->name('change_email');

Route::patch('settings/change/password', 'SettingsController@change_password')->name('change_password');

Route::get('feedback', 'FeedbackController@page')->name('feedback');

Route::post('feedback', 'FeedbackController@send_message')->name('send_message');

Route::resource('branches', 'BranchController');

resources/views/dashboard.blade.php
<!doctype html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>CMT Realtors | @yield('title')</title>
        <!-- jquery -->
        <script src="{{ Asset('vendor/jquery.js') }}"></script>
        <!-- bootstrap -->
        <link rel="stylesheet" href="{{ Asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <script src="{{ Asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
        <!-- font-awesome -->
        <link rel="stylesheet" href="{{ Asset('vendor/font-awesome/css/font-awesome.min.css') }}">
        <!-- css -->
        <link rel="stylesheet" href="{{ asset('css/dashboard/style.css') }}">
        @yield('css')
    </head>

    <body>
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="" class="navbar-brand">
                        <span>cmt</span>&nbsp;<sup>realtors</sup>
                    </a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="fa fa-user"></i>
                            {{ Auth::user()->name }} 
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                    Logout
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="aside-menu">
            <ul>
                <li>
                    <a href="{{ route('instructions.create') }}" class="btn clearfix" id="new-instruction">
                        <span class="pull-left">
                            new instruction
                        </span>
                        <span class="pull-right">
                            <i class="fa fa-plus"></i>
                        </span>
                    </a>
                </li>
                @if(Auth::user()->isAdmin)
                    <li>
                        <a href="{{ route('members.index') }}">
                            <i class="fa fa-user"></i>
                            members
                        </a>
                        <a href="{{ route('members.create') }}" class="pull-right add">
                            add
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('branches.index') }}">
                            <i class="fa fa-building"></i>
                            branches
                        </a>
                        <a href="{{ route('branches.create') }}" class="pull-right add">
                            add
                        </a>
                    </li>
                @endif
                <li>
                    <a href="{{ route('instructions.index') }}">
                        <i class="fa fa-briefcase"></i>
                        instructions
                    </a>
                </li>
                <li>
                    <a href="{{ route('settings') }}">
                        <i class="fa fa-cog"></i>
                        settings
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-home"></i>
                        home
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="{{ route('feedback') }}">
                        feedback
                    </a>
                </li>
            </ul>
            <div id="briwan">
                <a href="">
                    powered by BRIWAN
                </a>
            </div>
            <div id="footer">
                &copy; - {{ date('Y') }}. cmt realtors
            </div>
        </div>
        <div id="content">
            @yield('content')
        </div>
        @yield('js')
    </body>

</html>

resources/views/feedback.blade.php
@extends('dashboard')

@section('title')
    settings
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/forms/style.css') }}">
@endsection

@section('content')
    <div class="media">
        <div class="media-left">
            <i class="fa fa-envelope media-object"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                Send message about any issue
            </h4>
            <form action="{{ route('send_message') }}" class="form-horizontal" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="message" class="control-label col-md-3 col-sm-3">
                        Feedback:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="message" name="message" required autofocus placeholder="Enter your message">
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <button type="submit" class="btn">
                            send
                        </button>
                    </div>
                </div>
            </form>
            @if(session('success'))
                <p class="alert-success">{{ session()->get('success') }}</p>
            @endif
        </div>
    </div>
@endsection

resources/views/home.blade.php
<!doctype html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            {{ config('app.name') }}
        </title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if (Auth::check())
                        <a href="{{ route('instructions.index') }}">
                            Instructions
                        </a>
                    @else
                        <a href="{{ url('/login') }}">Login</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    {{ config('app.name') }}
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/master.blade.php
<!doctype html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>CMT Realtors | @yield('title')</title>
        <!-- jquery -->
        <script src="{{ Asset('vendor/jquery.js') }}"></script>
        <!-- bootstrap -->
        <link rel="stylesheet" href="{{ Asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <script src="{{ Asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
        <!-- font-awesome -->
        <link rel="stylesheet" href="{{ Asset('vendor/font-awesome/css/font-awesome.min.css') }}">
        <!-- css -->
        @yield('css')
    </head>

    <body>
        @yield('content')
    </body>

</html>