routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return view('home');
});

Route::get('instructions/search', 'InstructionDetailController@filter')->name('instrunctions.search');

Route::resource('instructions', 'InstructionDetailController');

Route::patch('instructions/{instruction}/delivered', 'InstructionDetailController@delivered')->name('instruction.delivered');

Route::get('members', 'BranchMembersController@index')->name('members.index');

Route::get('members/create', 'BranchMembersController@create')->name('members.create');

Route::post('members', 'BranchMembersController@store')->name('members.store');

Route::delete('members/{member}', 'BranchMembersController@destroy')->name('members.destroy');

Route::get('account_registered', 'BranchMembersController@account_registered')->name('account_registered');

Route::post('activate_account', 'BranchMembersController@activate_account')->name('activate_account');

Auth::routes();

Route::get('settings', 'SettingsController@page')->name('settings');

Route::patch('settings/change/email', 'SettingsController@change_email')->name('change_email');

Route::patch('settings/change/password', 'SettingsController@change_password')->name('change_password');

Route::get('feedback', 'FeedbackController@page')->name('feedback');

Route::post('feedback', 'FeedbackController@send_message')->name('send_message');

Route::resource('branches', 'BranchController');

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    protected $fillable = ['name'];

    public function members()
    {
        return $this->hasMany(User::class);
    }

    public function instructions()
    {
        return $this->hasMany(InstructionDetail::class);
    }
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Branch;
use Session;

class BranchController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = Branch::orderBy('created_at', 'desc')->get();

        return view('branches.index', compact('branches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branches.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        Branch::create($request->all());

        return redirect(route('branches.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function edit(Branch $branch)
    {
        return view('branches.edit', compact('branch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Branch $branch)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $branch->update($request->all());

        Session::flash('success', 'Branch name has been updated successfully');

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Branch  $branch
     * @return \Illuminate\Http\Response
     */
    public function destroy(Branch $branch)
    {
        $branch->delete();

        return redirect(route('branches.index'));
    }
}

resources/views/branches/create.blade.php
@extends('dashboard')

@section('title')
    create new branch
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/forms/style.css') }}">
@endsection

@section('content')
    <div class="media">
        <div class="media-left">
            <i class="fa fa-building media-object"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                create new branch
            </h4>
            <form action="{{ route('branches.store') }}" class="form-horizontal" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name" class="control-label col-md-3 col-sm-3">
                        Name:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="name" name="name" required autofocus value="{{ old('name') }}" placeholder="Enter name of the branch">
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <button type="submit" class="btn">
                            save
                        </button>
                    </div>
                    @if($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/branches/edit.blade.php
@extends('dashboard')

@section('title')
    edit {{ $branch->name }} branch
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/forms/style.css') }}">
@endsection

@section('content')
    <div class="media">
        <div class="media-left">
            <i class="fa fa-building media-object"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                Edit branch
            </h4>
            <form action="{{ route('branches.update', $branch->id) }}" class="form-horizontal" method="post">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name" class="control-label col-md-3 col-sm-3">
                        Name:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="name" name="name" required autofocus value="{{ $branch->name }}" placeholder="Enter name of the branch">
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <button type="submit" class="btn">
                            save
                        </button>
                    </div>
                    @if($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
            </form>
            @if(session('success'))
                <p class="alert-success">
                    {{ session()->get('success') }}
                </p>
            @endif
        </div>
    </div>
@endsection

resources/views/branches/index.blade.php
@extends('dashboard')

@section('title', 'branches')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/branches/index.css') }}">
@endsection

@section('content')
    <div class="media">
        <div class="media-left">
            <i class="fa fa-building media-object"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                branches
            </h4>
            <table>
                @foreach($branches as $branch)
                    <tr>
                        <td>
                            {{ $loop->iteration }}. {{ $branch->name }}
                        </td>
                        <td>
                            <a href="{{ route('branches.edit', $branch->id) }}">
                                edit
                            </a>
                            &nbsp; | &nbsp;
                            <form action="{{ route('branches.destroy', $branch->id) }}" method="post">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" onclick="javascript:return confirm('Are you surer to delete this branch')" id="delete">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection