routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    
    return view('home');
});

Route::get('instructions/search', 'InstructionDetailController@filter')->name('instrunctions.search');

Route::resource('instructions', 'InstructionDetailController');

Route::patch('instructions/{instruction}/delivered', 'InstructionDetailController@delivered')->name('instruction.delivered');

Route::get('members', 'BranchMembersController@index')->name('members.index');

Route::get('members/create', 'BranchMembersController@create')->name('members.create');

Route::post('members', 'BranchMembersController@store')->name('members.store');

Route::delete('members/{member}', 'BranchMembersController@destroy')->name('members.destroy');

Route::get('account_registered', 'BranchMembersController@account_registered')->name('account_registered');

Route::post('activate_account', 'BranchMembersController@activate_account')->name('activate_account');

Auth::routes();

Route::get('settings', 'SettingsController@page')->name('settings');

Route::patch('settings/change/email', 'SettingsController@change_email')->name('change_email');

Route::patch('settings/change/password', 'SettingsController@change_password')->name('change_password');

Route::get('feedback', 'FeedbackController@page')->name('feedback');

Route::post('feedback', 'FeedbackController@send_message')->name('send_message');

Route::resource('branches', 'BranchController');

app/InstructionDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
use Illuminate\Notifications\Notifiable;

class InstructionDetail extends Model
{
    use BranchInstruction;
    use Notifiable;

    protected $dates = ['track_time', 'delivery_date'];

    protected $fillable = [
        'bank', 'bank_branch', 'client_contacts', 'track_time', 'title_no', 'branch_id', 'expenditure', 'user_id', 'payment', 'status'
    ];

    public function branch()
    {
        return $this->belongsTo('App\Branch');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function routeNotificationForMail()
    {
        return $this->user->email;
    }

    public function short_desc()
    {
        return substr($this->title_no, 0, 32);
    }
}

app/Http/Controllers/InstructionDetailController.php
<?php

namespace App\Http\Controllers;

use App\InstructionDetail;
use App\Http\Requests\StoreInstructionDetail;
use Auth;
use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Notifications\InstructionDelivered;
use App\Branch;
use App\Http\Requests\UpdateInstructionDetail;
use App\Http\Requests\FilterRequest;
use App\User;

class InstructionDetailController extends Controller
{
    public  function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $instructions = InstructionDetail::orderBy('created_at', 'desc')->paginate(9);

        return view('instruction_details.index', compact('instructions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('instruction_details.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreInstructionDetail $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreInstructionDetail $request)
    {
        $instruction = InstructionDetail::make($request->all());

        if (Auth::user()->isAdmin)
        {
            $instruction->branch_id = User::find( $request->user_id )->branch->id;

            $instruction->user_id = $request->user_id;
        }
        else
        {
            $instruction->branch_id = Auth::user()->branch_id;

            $instruction->user_id = Auth::user()->id;
        }

        $instruction->save();

        return redirect(route('instructions.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\InstructionDetail  $instruction
     * @return \Illuminate\Http\Response
     */
    public function show(InstructionDetail $instruction)
    {
        return view('instruction_details.show', compact('instruction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\InstructionDetail  $instruction
     * @return \Illuminate\Http\Response
     */
    public function edit(InstructionDetail $instruction)
    {
        return view('instruction_details.edit', compact('instruction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateInstructionDetail  $request
     * @param  \App\InstructionDetail  $instruction
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateInstructionDetail $request, InstructionDetail $instruction)
    {
        $instruction->update($request->all());

        return redirect()->route('instructions.show', $instruction);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\InstructionDetail  $instruction
     * @return \Illuminate\Http\Response
     */
    public function destroy(InstructionDetail $instruction)
    {
        $instruction->delete();

        return redirect(route('instructions.index'));
    }

    public function delivered(InstructionDetail $instruction)
    {
        if ($instruction->status == 'pending')
        {
            $instruction->status = 'completed';
        }

        $instruction->delivery_date = Carbon::now();

        $instruction->save();

        $instruction->notify(new InstructionDelivered($instruction));

        return redirect(route('instructions.show', $instruction->id));
    }

    /**
     * Filter request
     * 
     * @param  \App\Http\Requests\FilterRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function filter(FilterRequest $request)
    {
        if ( $request->get('filter') == 'branch' )
        {
            $instructions = InstructionDetail::where(

                'branch_id',

                Branch::where('name', 'like', '%'. $request->get('query') .'%')->first()->id

            )->get();
        }

        else if ( $request->get('filter') == 'staff' )
        {
            $instructions = InstructionDetail::where(

                'user_id',

                User::where('name', 'like', '%'. $request->get('query') .'%')->first()->id

            )->get();
        }

        else if ( $request->get('filter') == 'status' )
        {
            $instructions = InstructionDetail::where(

                'status', $request->get('query')

            )->get();
        }

        else if ( $request->get('filter') == 'date' )
        {
            $instructions = InstructionDetail::where(

                'created_at', 'like', '%'. $request->get('query') .'%'

            )->get();
        }

        return view('instruction_details.search', compact('instructions'));
    }
}

resources/views/instruction_details/create.blade.php
@extends('dashboard')

@section('title')
    create new instruction
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/forms/style.css') }}">
@endsection

@section('content')
    <div class="media">
        <div class="media-left">
            <i class="fa fa-briefcase media-object"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                Create new instruction
            </h4>
            <form action="{{ route('instructions.store') }}" class="form-horizontal" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="bank" class="control-label col-md-3 col-sm-3">
                        Bank:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="bank" name="bank" value="{{ old('bank') }}" required autofocus placeholder="Enter name of the bank">
                    </div>
                    @if($errors->has('bank'))
                        <span class="help-block">
                            <strong>{{ $errors->first('bank') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="bank_branch" class="control-label col-md-3 col-sm-3">
                        Branch:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="bank_branch" name="bank_branch" value="{{ old('bank_branch') }}"  required placeholder="Enter bank branch">
                    </div>
                    @if($errors->has('bank_branch'))
                        <span class="help-block">
                            <strong>{{ $errors->first('bank_branch') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="client_contacts" class="control-label col-md-3 col-sm-3">
                        Client contacts:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="tel" class="form-control" id="client_contacts" name="client_contacts" value="{{ old('client_contacts') }}" required placeholder="Enter client mobile number">
                    </div>
                    @if($errors->has('client_contacts'))
                        <span class="help-block">
                            <strong>{{ $errors->first('client_contacts') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="track_time" class="control-label col-md-3 col-sm-3">
                        Track time:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="date" class="form-control" id="track_time" name="track_time" value="{{ old('track_time') }}" required>
                    </div>
                    @if($errors->has('track_time'))
                        <span class="help-block">
                            <strong>{{ $errors->first('track_time') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="title_no" class="control-label col-md-3 col-sm-3">
                        Title no:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="title_no" name="title_no" value="{{ old('title_no') }}" required placeholder="Enter instruction title details">
                    </div>
                    @if($errors->has('title_no'))
                        <span class="help-block">
                            <strong>{{ $errors->first('title_no') }}</strong>
                        </span>
                    @endif
                </div>
                @if(Auth::user()->isAdmin)
                     <div class="form-group">
                        <label for="user_id" class="control-label col-md-3 col-sm-3">
                            Staff:
                        </label>
                        <div class="col-md-6 col-sm-6">
                            <select name="user_id" id="staff">
                                @foreach(App\User::where('isAdmin', '!=', '1')->get() as $user)
                                    <option value="{{ $user->id }}">
                                        {{ $user->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        @if($errors->has('user_id'))
                            <span class="help-block">
                                <strong>{{ $errors->first('user_id') }}</strong>
                            </span>
                        @endif
                    </div>
                @endif
                <div class="form-group">
                    <label for="expenditure" class="control-label col-md-3 col-sm-3">
                        Expenditure:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="expenditure" name="expenditure" value="{{ old('expenditure') }}" required placeholder="Enter money requisition">
                    </div>
                    @if($errors->has('expenditure'))
                        <span class="help-block">
                            <strong>{{ $errors->first('expenditure') }}</strong>
                        </span>
                    @endif
                </div>
                <button class="btn form-control" type="submit">
                    submit
                </button>
            </form>
        </div>
    </div>
@endsection

resources/views/instruction_details/edit.blade.php
@extends('dashboard')

@section('title')
    Edit instruction
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('css/forms/style.css') }}">
@endsection

@section('content')
    <div class="media">
        <div class="media-left">
            <i class="fa fa-briefcase media-object"></i>
        </div>
        <div class="media-body">
            <h4 class="media-heading">
                Edit instruction
            </h4>
            <form action="{{ route('instructions.update', $instruction) }}" class="form-horizontal" method="post">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="bank" class="control-label col-md-3 col-sm-3">
                        Bank:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="bank" name="bank" value="{{ $instruction->bank }}" required autofocus placeholder="Enter name of the bank">
                    </div>
                    @if($errors->has('bank'))
                        <span class="help-block">
                            <strong>{{ $errors->first('bank') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="bank_branch" class="control-label col-md-3 col-sm-3">
                        Branch:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="bank_branch" name="bank_branch" value="{{ $instruction->bank_branch }}"  required placeholder="Enter bank branch">
                    </div>
                    @if($errors->has('bank_branch'))
                        <span class="help-block">
                            <strong>{{ $errors->first('bank_branch') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="client_contacts" class="control-label col-md-3 col-sm-3">
                        Client contacts:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="tel" class="form-control" id="client_contacts" name="client_contacts" value="{{ $instruction->client_contacts }}" required placeholder="Enter client mobile number">
                    </div>
                    @if($errors->has('client_contacts'))
                        <span class="help-block">
                            <strong>{{ $errors->first('client_contacts') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="track_time" class="control-label col-md-3 col-sm-3">
                        Track time:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="date" class="form-control" id="track_time" name="track_time" value="{{ $instruction->track_time->format('Y-m-d') }}" required>
                    </div>
                    @if($errors->has('track_time'))
                        <span class="help-block">
                            <strong>{{ $errors->first('track_time') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group">
                    <label for="title_no" class="control-label col-md-3 col-sm-3">
                        Title no:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="title_no" name="title_no" value="{{ $instruction->title_no }}" required placeholder="Enter instruction title details">
                    </div>
                    @if($errors->has('title_no'))
                        <span class="help-block">
                            <strong>{{ $errors->first('title_no') }}</strong>
                        </span>
                    @endif
                </div>
                @if(Auth::user()->isAdmin)
                     <div class="form-group">
                        <label for="user_id" class="control-label col-md-3 col-sm-3">
                            Staff:
                        </label>
                        <div class="col-md-6 col-sm-6">
                            <select name="user_id" id="staff">
                                @foreach(App\User::where('isAdmin', '!=', '1')->get() as $user)
                                    <option value="{{ $user->id }}" {{ ($instruction->user_id == $user->id ? 'selected' : '') }}>
                                        {{ $user->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        @if($errors->has('user_id'))
                            <span class="help-block">
                                <strong>{{ $errors->first('user_id') }}</strong>
                            </span>
                        @endif
                    </div>
                @endif
                <div class="form-group">
                    <label for="expenditure" class="control-label col-md-3 col-sm-3">
                        Expenditure:
                    </label>
                    <div class="col-md-6 col-sm-6">
                        <input type="text" class="form-control" id="expenditure" name="expenditure" value="{{ $instruction->expenditure }}" required placeholder="Enter money requisition">
                    </div>
                    @if($errors->has('expenditure'))
                        <span class="help-block">
                            <strong>{{ $errors->first('expenditure') }}</strong>
                        </span>
                    @endif
                </div>
                @if( $instruction->delivery_date != null )
                    <div class="form-group">
                        <label for="payment" class="control-label col-md-3 col-sm-3">
                            Payment:
                        </label>
                        <div class="col-md-6 col-sm-6">
                            <select name="payment" id="payment">
                                <option value="not paid" @if($instruction->payment == 'not paid') selected @endif>
                                    Not paid
                                </option>
                                <option value="paid" @if($instruction->payment == 'paid') selected @endif>
                                    Paid
                                </option>
                            </select>
                        </div>
                        @if($errors->has('payment'))
                            <span class="help-block">
                                <strong>{{ $errors->first('payment') }}</strong>
                            </span>
                        @endif
                    </div>
                @endif
                <button class="btn form-control" type="submit">
                    submit
                </button>
            </form>
        </div>
    </div>
@endsection

resources/views/instruction_details/index.blade.php
@extends('dashboard')

@section('title')
    Instruction details list
@endsection

@section('css')
    <link rel="stylesheet" href="{{ Asset('css\instruction_details\index.css') }}">
@endsection

@section('content')
    <form action="{{ route('instrunctions.search') }}" class="form-inline" id="search-form">
        <label class="text-uppercase">
            filter by:
        </label>
        <div class="input-group">
            <select name="filter" class="form-control" required id="filter">
                <option value="status">status</option>
                <option value="date">date</option>
                @if(Auth::user()->isAdmin)
                    <option value="staff">staff</option>
                    <option value="branch">branch</option>
                @endif
            </select>
        </div>
        <div class="input-group">
            <input type="search" class="form-control" placeholder="Type search query" required name="query" id="query">
        </div>
        <button type="submit" class="btn btn-success text-uppercase">
            search
        </button>
    </form>
    <table>
        <tr id="table-head">
            <th>status</th>
            <th>title no</th>
            <th>posted</th>
            <th>track time</th>
        </tr>
        @foreach($instructions as $instruction)
            <tr>
                <td id="status">
                    @if($instruction->status == 'pending')
                        <i class="fa fa-calendar-plus-o pending"></i>
                        pending
                    @elseif($instruction->status == 'completed')
                        <i class="fa fa-calendar-check-o completed"></i>
                        completed:
                        <span>
                            {{ $instruction->delivery_date->format('j F Y') }}
                        </span>
                    @else
                        <i class="fa fa-calendar-times-o expired"></i>
                        expired:
                        @if( $instruction->delivery_date != null )
                            {{ $instruction->delivery_date->format('j F Y') }}
                        @else
                            not delivered
                        @endif
                    @endif
                </td>
                <td id="desc">
                    {{ $instruction->short_desc() }}
                    <span>-</span>
                </td>
                <td>
                    {{ $instruction->created_at->format('j F Y') }}
                </td>
                <td>
                    {{ $instruction->track_time->format('j F Y') }}
                </td>
                <td>
                    <div class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="fa fa-ellipsis-h"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" role="menu">
                            <li>
                                <a href="{{ route('instructions.show', $instruction->id) }}">
                                    <i class="fa fa-eye"></i>
                                    &nbsp; view
                                </a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
    {{ $instructions->links() }}
@endsection

@section('js')
    <script src="{{ asset('js/search-form.js') }}"></script>
@endsection

resources/views/instruction_details/show.blade.php
@extends('dashboard')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/instruction_details/show.css') }}">
@endsection

@section('title')
    {{ $instruction->short_desc() }}
@endsection

@section('content')
    <h4 id="status">
        current status:
        @if($instruction->status == 'pending')
            <i class="fa fa-calendar-plus-o pending"></i>
            pending
        @elseif($instruction->status == 'completed')
            <i class="fa fa-calendar-check-o completed"></i>
            completed
        @else
            <i class="fa fa-calendar-times-o expired"></i>
            expired
        @endif
        @can('update', $instruction)
            <small class="pull-right">
                <a href="{{ route('instructions.edit', $instruction->id) }}" class="btn btn-link">
                    <i class="fa fa-pencil-square-o"></i>
                    edit
                </a>
            </small>
        @endcan
        @can('delete', $instruction)
            <small class="pull-right">
                <form action="{{ route('instructions.destroy', $instruction->id) }}" method="post" class="pull-right">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <button onclick="javascript:return confirm('Are you sure to delete this item?')" type="submit" class="btn btn-link">
                        <i class="fa fa-trash"></i>
                        delete
                    </button>
                </form>
            </small>
        @endcan
    </h3>
    <div class="media">
        <div class="media-left media-middle">
            <i class="fa fa-building media-object" aria-hidden="true"></i>
        </div>
        <div class="media-body">
             <h2>
                branch
                <small>
                    < {{ $instruction->branch->name }} >
                </small>
                @if($instruction->delivery_date == null)
                    @can('update', $instruction)
                        <form action="{{ route('instruction.delivered', ['instruction' => $instruction->id]) }}" method="post" class="pull-right" id="deliver">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn">
                                mark as delivered
                            </button>
                        </form>
                    @endcan
                @else
                    <small class="pull-right" id="delivered">
                        <i class="fa fa-check-circle" aria-hidden="true"></i>
                        &nbsp; delivered on {{ $instruction->delivery_date->format('j F Y') }}
                    </small>      
                @endif
             </h2>
             <h6>
                posted on {{ $instruction->created_at->format('j F Y') }}
            </h6>
            <h6 id="track_time">
                track time <span>{{ $instruction->track_time->format('j F Y') }}</span>
            </h6>
        </div>
    </div>
    <p id="title_no">
        {{ $instruction->title_no }}
    </p>
    <h5>
        <b>bank:</b> 
        {{ $instruction->bank }} - {{ $instruction->bank_branch }}
    </h5>
    <h5>
        <b>client contacts:</b>
        {{ $instruction->client_contacts }}
    </h5>
    @if( $instruction->delivery_date != null )
        <h5>
            <b>client invoice:</b>
            {{ $instruction->payment }}
        </h5>
    @endif
    <h5>
        <b>expenditure:</b>
        KES. {{ number_format($instruction->expenditure) }}
    </h5>
    @if(Auth::user()->isAdmin)
        <h5>
            <b>assigned to:</b>
            <span class="text-capitalize">
                {{ $instruction->user->name }}
            </span>
        </h5>
    @endif
    <h5>

    </h5>
@endsection